### ISSUE TITLE
Error running Functional Tests in Analytics.Core

### ISSUE THREAD

**Issue by tmaly-spr** [relativitydev/relativity.testing.framework.api#212]
### Describe the bug

After successfully running the test build on Analytics.Core - (.\build.ps1 -taskList Compile, Test), the follwing exception is being thrown when the functional tests are run:

Message: 
OneTimeSetUp: System.InvalidOperationException : Unable to initialize Relativity.Testing.Framework.Api.ApiComponent.
  ----> Castle.MicroKernel.ComponentNotFoundException : No component for supporting the service Relativity.Testing.Framework.Api.Interceptors.ApplicationInsightsEventInterceptor was found

  

### Steps to Reproduce

in analytics.core execute .\build.ps1 -taskList Compile, Test
in the VS Test Explorer run any functional test 

### Relativity.Testing.Framework Version

2.0.2 / 7.0.0

### Relativity.Testing.Framework.API Version

1.2.3 / 5.6.1

### Relativity environment installation Type

RelativityOne

### Environment version

Latest

### Test Case

Analytics.Conceptual.NUnit.FunctionalTests.CategorizationSet.SVM.AnalyticsCategory.CRUD.CategorizationSetTestFixture

### Expected Behavior

The tests should run

### Actual Behavior

Tests throw an exception: Message: 
OneTimeSetUp: System.InvalidOperationException : Unable to initialize Relativity.Testing.Framework.Api.ApiComponent.
  ----> Castle.MicroKernel.ComponentNotFoundException : No component for supporting the service Relativity.Testing.Framework.Api.Interceptors.ApplicationInsightsEventInterceptor was found

**Comment by paulletang** [comment]
Is `2.0.2 / 7.0.0` indicating that you tried this with both versions, and it's present in both?

**Comment by tmaly-spr** [comment]
![image](https://user-images.githubusercontent.com/75339501/135879856-6893ef02-cf40-4091-a3ae-310f204292a4.png)

**Comment by tmaly-spr** [comment]
I guess the version is 2.0.2. I included the other as I wasn't sure which was correct.

**Comment by briantoms** [comment]
The first number listed there is the currently-installed version; the second number is the latest published version that can be upgraded to.

Do you have `<Parameter name="EnableApplicationInsights" value="false" />` in your runsettings file? If so, try removing that (or updating to RTF.API 3.12.1 or newer) and try running the tests again.
