### ISSUE TITLE
Creating a view for an object type other than Document still creates the view under the Document object type

### ISSUE THREAD

**Issue by robertbohar** [relativitydev/relativity.testing.framework.api#255]
### Describe the bug

The object type parameter is not being passed to the view creation api which is causing any view to be created as a default document view.
`

### Steps to Reproduce

`_viewService.Create(_workspace.ArtifactID,
    new View
    {
        Name = _VIEW_NAME,
        ObjectType = new NamedArtifact { Name = "Field" },
        SearchCriteria = viewCriteria,
        Fields = new[] { new NamedArtifact { Name = "Artifact ID" }
        VisibleInDropdown = true
    }
);
`

### Relativity.Testing.Framework Version

6.4.0

### Relativity.Testing.Framework.API Version

5.9.0

### Relativity environment installation Type

Relativity Server

### Environment version

12.3.120.8 (sundrop-eau)

### Expected Behavior

The view should be created under the Field object type.

### Actual Behavior

The view is being created under the Document object type.

### Screenshots

![image](https://user-images.githubusercontent.com/95496711/144649060-63c317de-7011-452a-a175-5f16493b76b3.png)

**Comment by briantoms** [comment]
This is seemingly an issue with the underlying Relativity API. Passing `ObjectType` on a create request seems to be ignored; `ArtifactTypeID` determines the object type of the view.

This doesn't seem to be fixable within Relativity.Testing.Framework.API, and specifying `ArtifactTypeID` works to specify the object type.
