### ISSUE TITLE
IWorkspaceService hangs

### ISSUE THREAD

**Issue by meggers** [relativitydev/relativity.testing.framework.api#261]
### Describe the bug

Trying to resolve IWorkspaceService in test setup fixture on local development machine hangs for an indeterminate amount of time.

`RelativityFacade.Instance.Resolve<IWorkspaceService>()`

### Steps to Reproduce

Using RTF RingSetup 0.17.0 / RTF.Api 6.0.0
Using new aio-sundrop-1 TestVM
Using test settings generated from .\DevelopmentScripts\New-TestSettings.ps1 in RAP CD template repository
Using Microsoft Visual Studio Professional 2019 Version 16.11.7

```			
Dictionary<string, string> additionalSettings = new Dictionary<string, string>()
{
    ["PerformRelativityVersionCheck"] = "false"
};

IConfigurationRoot configurationRoot = new ConfigurationBuilder()
    .AddNUnitParameters()
    .AddEnvironmentVariables()
    .AddInMemoryCollection(additionalSettings)
    .Build();

RelativityFacade.Instance.RelyOn(new CoreComponent { ConfigurationRoot = configurationRoot });
RelativityFacade.Instance.RelyOn<ApiComponent>();
var workspaceService = RelativityFacade.Instance.Resolve<IWorkspaceService>();
```

### Relativity.Testing.Framework Version

7.1.0

### Relativity.Testing.Framework.API Version

6.0.0

### Relativity environment installation Type

Relativity Server

### Environment version

Sundrop 1

### Expected Behavior

I expect the workspace service to resolve quickly, or fail to resolve quickly, or show messaging indicating cause of long resolution

### Actual Behavior

The resolve hangs for some amount of time (at least over two hours observed)

**Comment by paulletang** [comment]
@meggers Does RingSetup run before the code block you posted, or is what you posted there functionally the only thing that runs when you encounter this?

**Comment by paulletang** [comment]
Are there any toggles/instance settings being set before you get here, or is this a fresh deployment?

**Comment by meggers** [comment]
Thanks @paulletang!

_Does RingSetup run before the code block you posted, or is what you posted there functionally the only thing that runs when you encounter this?_

Nope, this is run in a fixture annotated with [SetUpFixture, Order(1)] that is intended to set up artifacts used by a TestSetup fixture for TestVM/hopper testing.

Are there any toggles/instance settings being set before you get here, or is this a fresh deployment?

This is a fresh deployment. Create testvm -> run test -> hang

**Comment by paulletang** [comment]
I was unable to reproduce this using the Sundrop 1 image, and Max was able to confirm that this works when testing against a brand new image in hopper.
This appears to be an issue with the setup of the environment.

@meggers Please reopen this issue and/or make a new ticket with TestEngineering/EngineeringInsights if you get new information that indicates otherwise.
