### ISSUE TITLE
Workspace SQL Database is wrongly being created in the EDDS level database

### ISSUE THREAD

**Issue by ryanc-relativity** [relativitydev/relativity.testing.framework.api#264]
### Describe the bug

When calling the workspace creation [ _workspaceService.Create(workspaceEntity)](https://git.kcura.com/projects/AN/repos/analytics-active-learning/browse/Source/Analytics.ActiveLearning.FunctionalTests/ContinuousIntegrationTests/HelperClasses/TestDataObjectFactory.cs#34-39) in the Active Learning solution, it creates the workspace database in the EDDS level db.  See attached picture for more information:

### Steps to Reproduce

1. Build the Active Learning solution with x64 processor architecture in Visual Studio
2. Run this suite: [link](https://git.kcura.com/projects/AN/repos/analytics-active-learning/browse/Source/Analytics.ActiveLearning.FunctionalTests/ContinuousIntegrationTests/Tests/Smoke/SmokeAndRmtTests.cs)
3. This [line](https://git.kcura.com/projects/AN/repos/analytics-active-learning/browse/Source/Analytics.ActiveLearning.FunctionalTests/ContinuousIntegrationTests/Tests/Fixtures/WorkspaceSetupFixture.cs#276) might need to be skipped for it to work.
4. Verify db creation after this line [ _workspaceService.Create(workspaceEntity](https://git.kcura.com/projects/AN/repos/analytics-active-learning/browse/Source/Analytics.ActiveLearning.FunctionalTests/ContinuousIntegrationTests/HelperClasses/TestDataObjectFactory.cs#34-39)

### Relativity.Testing.Framework Version

6.0.1

### Relativity.Testing.Framework.API Version

6.0.1

### Relativity environment installation Type

RelativityOne

### Environment version

12.2.224.7

### Test Case

https://git.kcura.com/projects/AN/repos/analytics-active-learning/browse/Source/Analytics.ActiveLearning.FunctionalTests/ContinuousIntegrationTests/Tests/Smoke/SmokeAndRmtTests.cs

### Expected Behavior

Workspace database being created in the workspace level database (as opposed to EDDS).  Workspace shows up in the UI.

### Actual Behavior

Workspace database is being created in the EDDS level database (when it's supposed to be the workspace one).  Workspace shows up in the UI, despite not being set up in the right location.

### Screenshots

![image](https://user-images.githubusercontent.com/46359212/150877219-21b8018d-7e65-41e8-8de0-a416eed466c6.png)

**Comment by Sai-Nissankula** [comment]
Hi @ryanc-relativity , I am looking into this. Will create a jira ticket too.

**Comment by briantoms** [comment]
Looks like this is working as intended from the RTF perspective. When no resource pool is specified on the workspace create request, RTF defaults to using the first listed resource pool, which is usually `Default - DO NOT USE` on internal RelativityOne regression environments. It also uses the first SQL server listed for the resource pool, which in this case is the EDDS SQL server.

RingSetup explicitly creates a workspace in the `RelativityOne Pool` resource pool. If these tests are intended to be run on RelativityOne environments, they should do the same.

**Comment by briantoms** [comment]
After discussing with the team, we have decided to update RTF.API's behavior to prefer the `RelativityOne Pool` resource pool if it exists.
